#ifdef INSTANCE_EXTENSIONS
VK_KHR_SURFACE_EXTENSION_NAME,

#ifdef PLATFORM_WINDOWS
VK_KHR_WIN32_SURFACE_EXTENSION_NAME,
#endif

#ifdef DEBUG_EXTENSIONS
VK_EXT_DEBUG_UTILS_EXTENSION_NAME
#endif
#endif

#ifdef DEVICE_EXTENSIONS
VK_KHR_SWAPCHAIN_EXTENSION_NAME
#endif

#ifdef LAYERS
"VK_LAYER_LUNARG_standard_validation"
#endif
